name: Deploy Hugo Site

# 触发 workflow 的条件
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Deploy
        uses: burnett01/rsync-deployments@6.0.0
        with:
          # 复制操作的参数。"-avzr --delete"意味部署时清空服务器目标目录下的文件
          switches: -avzr --delete
          # 相对于仓库根目录的路径
          path: './'
          
          # 服务器的域名/IP
          # remote_host: ${{ secrets.DEPLOY_HOST }}
          # remote_host: xiaobluebird.com
          remote_host: '47.97.5.17'
          
          # 服务器中的目标路径
          # remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_path: '/usr/local/blog/public/'
         
          # 服务器ssh端口(默认22,可改
          # remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_port: '22'
          
          # 服务器默认用户名为root(不建议使用root账号)
          REMOTE_USER: 'root'
          #remote_user: ${{ secrets.DEPLOY_USER }}
          
          # 私钥
          remote_key: '${{ secrets.DEPLOY_KEY }}'
          
